-------------------------------------------------------- TRABAJO INTEGRADOR FINAL --------------------------------------------------------

-------------------------------------------------------- CREACION DE LA BASE DE DATOS --------------------------------------------------------

USE master; 
GO

CREATE DATABASE DBFerreteria
GO

-------------------------------------------------------- CREACION DE LAS TABLAS --------------------------------------------------------

USE DBFerreteria
GO

-- TABLA CATEGORIAS
CREATE TABLE CATEGORIAS
(
	Cod_CA CHAR(5) NOT NULL,
	Nombre_CA VARCHAR(20) NOT NULL,
	Descripcion_CA VARCHAR(30) NOT NULL,
	Imagen_CA VARCHAR(50) NULL,

	CONSTRAINT PK_CATEGORIAS PRIMARY KEY(Cod_CA),

)
GO
-- TABLA PERFILES
CREATE TABLE PERFILES
(
	Cod_PER CHAR(5) NOT NULL,
	Nombre_PER VARCHAR(20) NOT NULL,

	CONSTRAINT PK_PERFILES PRIMARY KEY(Cod_PER)
)
GO
--TABLA PROVINCIAS
CREATE TABLE PROVINCIAS
(
	Cod_PCIAS INT IDENTITY(1,1) NOT NULL,
	Nombre_PCIAS VARCHAR(15) NOT NULL,

	CONSTRAINT PK_PROVINCIAS PRIMARY KEY(Cod_PCIAS)
)
GO
--TABLA CIUDADES
CREATE TABLE CIUDADES
(
	CodCiudad_CIU INT IDENTITY(1,1) NOT NULL,
	CodProvincia_CIU INT NOT NULL,
	Nombre_CIU VARCHAR(15) NOT NULL,

	CONSTRAINT PK_CIUDADES PRIMARY KEY(CodCiudad_CIU),
     
	 CONSTRAINT FK_CIUDADES FOREIGN KEY(CodProvincia_CIU)
     REFERENCES PROVINCIAS (Cod_PCIAS)
)
GO
--	TABLA MARCAS
CREATE TABLE MARCAS
(
	Cod_MA CHAR(5) NOT NULL,
	Nombre_MA VARCHAR(20) NOT NULL,
	Descripcion_MA VARCHAR(30) NOT NULL,
	Imagen_MA VARCHAR(50) NULL,

	CONSTRAINT PK_MARCAS PRIMARY KEY(Cod_MA)
)
GO
-- TABLA MEDIOPAGOS
CREATE TABLE MEDIOPAGOS
(
	Cod_MP CHAR(2) NOT NULL,
	Nombre_MP VARCHAR(20),
	Detalles_MP VARCHAR(30),

	CONSTRAINT PK_MEDIOPAGOS PRIMARY KEY(Cod_MP)
)
GO
-- TABLA USUARIOS
CREATE TABLE USUARIOS
(
	Cuit_USU CHAR(20) NOT NULL,
	PerfilCod_USU CHAR(5) NOT NULL,
	Nombre_USU VARCHAR(15) NULL,
	Apellido_USU VARCHAR(15) NULL,
	Telefono_USU VARCHAR(20) NOT NULL,
	Email_USU VARCHAR(20) NOT NULL,
	Password_USU VARCHAR(20) NOT NULL,
	CodProvincia_USU INT NOT NULL, 
	CodCiudad_USU INT NOT NULL, 
	Imagen_USU VARCHAR(50) NULL,
	RazonSocial_USU VARCHAR(30) NULL,

	CONSTRAINT PK_USUARIOS PRIMARY KEY(Cuit_USU),

	CONSTRAINT FK_USUARIOS_PERFILES FOREIGN KEY(PerfilCod_USU)
		REFERENCES PERFILES(Cod_PER),

	CONSTRAINT FK_USUARIOS_CIUDADES FOREIGN KEY(CodCiudad_USU)
		REFERENCES CIUDADES(CodCiudad_CIU)

)
GO
-- TABLA ARTICULOS
CREATE TABLE ARTICULOS
(
	Cod_ART CHAR(5) NOT NULL,
	MarcaCod_ART CHAR(5) NOT NULL, --(o CodMarca_ART)
	CatCod_ART CHAR(5) NOT NULL,
	Nombre_ART VARCHAR(20) NOT NULL,
	Descripcion_ART VARCHAR (30) NOT NULL,
	Precio_ART DECIMAL(8,2) NOT NULL DEFAULT(0),
	Imagen_ART VARCHAR(50) NULL,
	Estado_ART BIT NOT NULL,

	CONSTRAINT PK_ARTICULOS PRIMARY KEY(Cod_ART),
	CONSTRAINT FK_ARTICULOS_MARCAS FOREIGN KEY(MarcaCod_ART)
		REFERENCES MARCAS(Cod_MA),
	CONSTRAINT FK_ARTICULOS_CATEGORIAS FOREIGN KEY(CatCod_ART)
		REFERENCES CATEGORIAS(Cod_CA)

)
GO
-- TABLA PROVEEDORES
CREATE TABLE PROVEEDORES
(
	Cuit_PROV CHAR (20) NOT NULL,
	ID_PROV	CHAR(10) NOT NULL,
	RazonSocial_PROV VARCHAR(30) NOT NULL,
	Contacto_PROV VARCHAR(40) NOT NULL,

	CONSTRAINT PK_PROVEEDORES PRIMARY KEY(Cuit_PROV),
	CONSTRAINT FK_PROVEEDORES_USUARIOS FOREIGN KEY(Cuit_PROV)
		REFERENCES USUARIOS(Cuit_USU)
)
GO
-- TABLA ARTXPROV
CREATE TABLE ARTXPROV
(
	Cod_AxP CHAR(5) NOT NULL,
	Cuit_AxP CHAR(20) NOT NULL,
	CodArt_AxP CHAR(5) NOT NULL,
	PrecioUnitario_AxP DECIMAL(8,2) NOT NULL DEFAULT(0),
	Stock_AxP INT NOT NULL,

	CONSTRAINT PK_ARTXPROV PRIMARY KEY(Cod_AxP),
	CONSTRAINT FK_ARTXPROV_PROVEEDORES FOREIGN KEY(Cuit_AxP)
		REFERENCES PROVEEDORES(Cuit_PROV),
	CONSTRAINT FK_ARTXPROV_ARTICULOS FOREIGN KEY(CodArt_AxP)
		REFERENCES ARTICULOS(Cod_ART)
)
GO

-- TABLA VENTAS
CREATE TABLE VENTAS
(
	Cod_V INT NOT NULL IDENTITY(1,1),
	CuitCli_V CHAR(20) NOT NULL,
	MedioPago_V CHAR(2) NOT NULL,
	Fecha_V DATETIME NOT NULL,
	Total_V DECIMAL(8,2) NOT NULL DEFAULT(0),

	CONSTRAINT PK_VENTAS PRIMARY KEY(Cod_V),
	CONSTRAINT FK_VENTAS_CLIENTES FOREIGN KEY(CuitCli_V)
		REFERENCES USUARIOS(Cuit_USU),
	CONSTRAINT FK_VENTAS_MEDIOPAGOS FOREIGN KEY(MedioPago_V)
		REFERENCES MEDIOPAGOS(Cod_MP)
)
GO
-- TABLA DETALLEVENTAS
CREATE TABLE DETALLEVENTAS
(
	CodVenta_DV INT NOT NULL,
	CodArtxProv_DV CHAR(5) NOT NULL,
	Unidades_DV INT NOT NULL DEFAULT(0),
	PrecioUnitario_DV DECIMAL (8,2) NOT NULL DEFAULT(0)

	CONSTRAINT PK_DETALLEVENTAS PRIMARY KEY(CodVenta_DV, CodArtxProv_DV),
	CONSTRAINT FK_DETALLEVENTAS_VENTAS FOREIGN KEY(CodVenta_DV)
		REFERENCES VENTAS(Cod_V),
	CONSTRAINT FK_DETALLEVENTAS_ARTXPROV FOREIGN KEY(CodArtxProv_DV)
		REFERENCES ARTXPROV(Cod_AxP)
)
GO
-------------------------------------------------------- PROCEDIMIENTOS ALMACENADOS --------------------------------------------------------
--CARGAR USUARIOS 
CREATE PROCEDURE SPAGREGARUSUARIO
(
	@Cuit_USU CHAR(20),
	@PerfilCod_USU CHAR(5),
	@Nombre_USU VARCHAR(15),
	@Apellido_USU VARCHAR(15),
	@Telefono_USU VARCHAR(20),
	@Email_USU VARCHAR(20),
	@Password_USU VARCHAR(20),
	@CodProvincia_USU INT, 
	@CodCiudad_USU INT, 
	@Imagen_USU VARCHAR(50),
	@RazonSocial_USU VARCHAR(30)
)
AS
INSERT INTO USUARIOS(
    Cuit_USU,
	PerfilCod_USU,
	Nombre_USU,
	Apellido_USU ,
	Telefono_USU ,
	Email_USU,
	Password_USU,
	CodProvincia_USU, 
	CodCiudad_USU , 
	Imagen_USU ,
	RazonSocial_USU 
)
VALUES 
(
 @Cuit_USU ,
	@PerfilCod_USU ,
	@Nombre_USU ,
	@Apellido_USU ,
	@Telefono_USU ,
	@Email_USU ,
	@Password_USU,
	@CodProvincia_USU , 
	@CodCiudad_USU , 
	@Imagen_USU ,
	@RazonSocial_USU 
)
GO
CREATE PROCEDURE SPMODIFICARUSUARIO 
(
	@Cuit_USU CHAR(20),
	@PerfilCod_USU CHAR(5),
	@Nombre_USU VARCHAR(15),
	@Apellido_USU VARCHAR(15),
	@Telefono_USU VARCHAR(20),
	@Email_USU VARCHAR(20),
	@CodProvincia_USU INT, 
	@CodCiudad_USU INT, 
	@Imagen_USU VARCHAR(50),
	@RazonSocial_USU VARCHAR(30)
)
AS
UPDATE USUARIOS SET PerfilCod_USU=@PerfilCod_USU,Nombre_USU=@Nombre_USU,Apellido_USU=@Apellido_USU,
Telefono_USU=@Telefono_USU,Email_USU=@Email_USU,CodProvincia_USU=@CodProvincia_USU,CodCiudad_USU=@CodCiudad_USU,
Imagen_USU=Imagen_USU,RazonSocial_USU=@RazonSocial_USU WHERE Cuit_USU=@Cuit_USU
GO
--CARGAR PROVEEDORES 
CREATE PROCEDURE SPAGREGARPROVEEDORES
(
	@Cuit_PROV CHAR (20),
	@ID_PROV CHAR(10),
	@RazonSocial_PROV VARCHAR(30),
	@Contacto_PROV VARCHAR(40)
)
AS
INSERT INTO PROVEEDORES
(
Cuit_PROV,
	ID_PROV,
	RazonSocial_PROV,
	Contacto_PROV
)
VALUES 
(
    @Cuit_PROV ,
	@ID_PROV,
	@RazonSocial_PROV,
	@Contacto_PROV
)
GO
--MODIFICAR PROVEEDORES
CREATE PROCEDURE SPMODIFICARPROVEEDORES
(
@Cuit_PROV CHAR (20),
	@ID_PROV	CHAR(10),
	@RazonSocial_PROV VARCHAR(30),
	@Contacto_PROV VARCHAR(40)
)
AS
UPDATE PROVEEDORES SET ID_PROV=@ID_PROV, RazonSocial_PROV=@RazonSocial_PROV,Contacto_PROV=@Contacto_PROV
WHERE Cuit_PROV=@Cuit_PROV
GO
---CARGAR CATEGORIAS 
CREATE PROCEDURE SPAGREGARCATEGORIA
(
    @Codigo_CA	CHAR(5),
	@Nombre_CA VARCHAR(20),
	@Descripcion_CA VARCHAR(30),
	@Imagen_CA VARCHAR(50)
)
AS
INSERT INTO Categorias
(
    Cod_CA,
	Nombre_CA,
	Descripcion_CA,
	Imagen_CA 
)
VALUES
(
    @Codigo_CA,
	@Nombre_CA,
	@Descripcion_CA,
	@Imagen_CA
)
GO
---MODIFICAR CATEGORIA
CREATE PROCEDURE SPMODIFICARCATEGORIA
(
	@Codigo_CA	CHAR(5),
	@Nombre_CA VARCHAR(20),
	@Descripcion_CA VARCHAR(30),
	@Imagen_CA VARCHAR(50)
)
AS
UPDATE CATEGORIAS SET Nombre_CA=@Nombre_CA,Descripcion_CA=@Descripcion_CA,Imagen_CA=@Imagen_CA
WHERE Cod_CA =@Codigo_CA
GO
--AGREGAR PERFIL 
CREATE PROCEDURE SPAGREGARPERFIL
(
 @Cod_PER CHAR(5),
 @Nombre_PER VARCHAR(20)
)
AS
INSERT INTO PERFILES
(
 Cod_PER,
 Nombre_PER 
)
VALUES(
 @Cod_PER,
 @Nombre_PER
)
GO
--MODIFICAR PERFIL
CREATE PROCEDURE SPMODIFICARPERFIL
(
 @Cod_PER CHAR(5),
 @Nombre_PER VARCHAR(20)
)
AS
UPDATE PERFILES SET Nombre_PER=@Nombre_PER WHERE Cod_PER=@Cod_PER
GO

--AGREGAR PROVINCIAS 
CREATE PROCEDURE SPAGREGARPROVINCIAS 
(
	@Nombre_PCIAS VARCHAR(15)
)
AS
INSERT INTO PROVINCIAS
(
 
 Nombre_PCIAS
)
VALUES 
(

@Nombre_PCIAS
)
GO
--MODIFICAR PROVINCIAS 
CREATE PROCEDURE SPMODIFICARPROVINCIAS
(
	@Cod_PCIAS INT,
	@Nombre_PCIAS VARCHAR(15)
)
AS 
UPDATE PROVINCIAS SET  Nombre_PCIAS=@Nombre_PCIAS 
WHERE Cod_PCIAS=@Cod_PCIAS
GO
--AGREGAR CIUDADES 
CREATE PROCEDURE SPAGREGARCIUDADES
(
	@CodProvincia_CIU INT,
	@Nombre_CIU VARCHAR(15)
)
AS
INSERT INTO CIUDADES 
(
	CodProvincia_CIU,
	Nombre_CIU 
)
VALUES 
(
@CodProvincia_CIU,
@Nombre_CIU
)
GO
--MODIFICAR CIUDADES
CREATE PROCEDURE SPMODIFICARCIUDADES
(
@CodCiudad_CIU INT,
 @CodProvincia_CIU INT,
	@Nombre_CIU VARCHAR(15)
)
AS
UPDATE CIUDADES SET CodProvincia_CIU=@CodProvincia_CIU,Nombre_CIU=@Nombre_CIU
WHERE CodCiudad_CIU = @CodCiudad_CIU
GO
-- AGREGAR MARCA
CREATE PROCEDURE SPAGREGARMARCA
(
	@Cod_MA CHAR(5),
	@Nombre_MA VARCHAR(20),
	@Descripcion_MA VARCHAR(30),
	@Imagen_MA VARCHAR(50)
)
AS
INSERT INTO Marcas
(
	Cod_MA,
	Nombre_MA,
	Descripcion_MA,
	Imagen_MA
)
VALUES
(
	@Cod_MA,
	@Nombre_MA,
	@Descripcion_MA,
	@Imagen_MA
)
GO

--MODIFICAR MARCAS
CREATE PROCEDURE SPMODIFICARMARCAS
(
	@Cod_MA CHAR(5),
	@Nombre_MA VARCHAR(20),
	@Descripcion_MA VARCHAR(30),
	@Imagen_MA VARCHAR(50)
)
AS
UPDATE MARCAS SET Nombre_MA=@Nombre_MA,Descripcion_MA=@Descripcion_MA,Imagen_MA=@Imagen_MA
WHERE Cod_MA =@Cod_MA
GO
--MEDIOPAGOS
CREATE PROCEDURE SPAGREGARMEDIOPAGOS
(
	@Cod_MP CHAR(2),
	@Nombre_MP VARCHAR(20),
	@Detalles_MP VARCHAR(30)
)
AS
INSERT INTO MEDIOPAGOS
(
  Cod_MP,
  Nombre_MP,
  Detalles_MP
)
VALUES 
(
 @Cod_MP,
 @Nombre_MP,
 @Detalles_MP
)
GO
--MODIFICAR MEDIOS DE PAGOS
CREATE PROCEDURE SPMODIFICARMEDIOPAGOS
(
	@Cod_MP CHAR(2),
	@Nombre_MP VARCHAR(20),
	@Detalles_MP VARCHAR(30)
)
AS
UPDATE MEDIOPAGOS SET Nombre_MP=@Nombre_MP,Detalles_MP=@Detalles_MP
WHERE Cod_MP=@Cod_MP
GO

--CARGAR ARTICULOS
CREATE PROCEDURE SPAGREGARARTICULO
(
	@Cod_ART CHAR(5),
	@MarcaCod_ART CHAR(5),
	@CatCod_ART CHAR(5),
	@Nombre_ART VARCHAR(20),
	@Descripcion_ART VARCHAR(30),
	@Precio_ART DECIMAL(8,2),
	@Imagen_ART VARCHAR(50),
	@Estado_ART BIT
)
AS
INSERT INTO ARTICULOS
(
	Cod_ART,
	MarcaCod_ART,
	CatCod_ART,
	Nombre_ART,
	Descripcion_ART,
	Precio_ART,
	Imagen_ART,
	Estado_ART
)
VALUES
(
	@Cod_ART,
	@MarcaCod_ART,
	@CatCod_ART,
	@Nombre_ART,
	@Descripcion_ART,
	@Precio_ART,
	@Imagen_ART,
	@Estado_ART
)
GO

-- MODIFICAR ARTICULO
CREATE PROCEDURE SPMODIFICARARTICULOS
(
	@Cod_ART CHAR(5),
	@MarcaCod_ART CHAR(5),
	@CatCod_ART CHAR(5),
	@Nombre_ART VARCHAR(20),
	@Descripcion_ART VARCHAR(30),
	@Precio_ART DECIMAL(8,2),
	@Imagen_ART VARCHAR(50),
	@Estado_ART BIT
)
AS
UPDATE ARTICULOS
SET
	MarcaCod_ART=@MarcaCod_ART,
	CatCod_ART=@CatCod_ART,
	Nombre_ART=@Nombre_ART,
	Descripcion_ART=@Descripcion_ART,
	Precio_ART=@Precio_ART,
	Imagen_ART=@Imagen_ART,
	Estado_ART=@Estado_ART

WHERE Cod_ART=@Cod_ART
GO
--DAR DE BAJA ARTICULO 
CREATE PROCEDURE SPDAARDEBAJAARTICULO 
(
 @Cod_ART CHAR(5),
 @Estado_ART BIT
)
AS 
UPDATE ARTICULOS SET Estado_ART=@Estado_ART
WHERE Cod_ART=@Cod_ART
GO
---AGREGAR ARTXPROV 
CREATE PROCEDURE SPAGREGARARTXPROV
(
	@Cod_AxP CHAR(5),
	@Cuit_AxP CHAR(20),
	@CodArt_AxP CHAR(5),
	@PrecioUnitario_AxP DECIMAL(8,2),
	@Stock_AxP INT
)
AS
INSERT INTO ARTXPROV 
(
	Cod_AxP,
	Cuit_AxP,
	CodArt_AxP,
	PrecioUnitario_AxP,
	Stock_AxP 
)
VALUES 
(
	@Cod_AxP,
	@Cuit_AxP ,
	@CodArt_AxP,
	@PrecioUnitario_AxP,
	@Stock_AxP
)
GO
CREATE PROCEDURE SPMODIFICARARTXPROV
(
 @Cod_AxP CHAR(5),
	@Cuit_AxP CHAR(20),
	@CodArt_AxP CHAR(5),
	@PrecioUnitario_AxP DECIMAL(8,2),
	@Stock_AxP INT
)
AS 
UPDATE ARTXPROV SET Cuit_AxP=@Cuit_AxP,CodArt_AxP=@CodArt_AxP,PrecioUnitario_AxP=@PrecioUnitario_AxP,Stock_AxP=@Stock_AxP
WHERE Cod_AxP=@Cod_AxP
GO
--CARGAR VENTAS 
CREATE PROCEDURE SPAGREGARVENTAS
(
	@CuitCli_V CHAR(20),
	@MedioPago_V CHAR(2),
	@Fecha_V DATETIME,
	@Total_V DECIMAL(8,2)
)
AS
INSERT INTO VENTAS(
    CuitCli_V ,
	MedioPago_V,
	Fecha_V ,
	Total_V
)
VALUES(
    @CuitCli_V ,
	@MedioPago_V,
	@Fecha_V ,
	@Total_V
)
GO
CREATE PROCEDURE SPMODIFICARVENTAS 
(
	@Cod_V INT,
	@CuitCli_V CHAR(20),
	@MedioPago_V CHAR(2),
	@Fecha_V DATETIME,
	@Total_V DECIMAL(8,2)
)
AS 
UPDATE VENTAS SET CuitCli_V=@CuitCli_V,MedioPago_V=@MedioPago_V,Fecha_V=@Fecha_V,Total_V=@Total_V
WHERE Cod_V=@Cod_V
GO

CREATE PROCEDURE SPDETALLEVENTAS
(
	@CodVenta_DV INT,
	@CodArtxProv_DV CHAR(5),
	@Unidades_DV INT ,
	@PrecioUnitario_DV DECIMAL (8,2)
)
AS
INSERT INTO DETALLEVENTAS
(
   CodVenta_DV,
	CodArtxProv_DV,
	Unidades_DV ,
	PrecioUnitario_DV
)
VALUES (
	@CodVenta_DV,
	@CodArtxProv_DV,
	@Unidades_DV ,
	@PrecioUnitario_DV
)
GO
CREATE PROCEDURE SPMODIFICARDETALLEVENTAS
(
 @CodVenta_DV INT,
	@CodArtxProv_DV CHAR(5),
	@Unidades_DV INT ,
	@PrecioUnitario_DV DECIMAL (8,2)
)
AS 
UPDATE DETALLEVENTAS SET CodArtxProv_DV=@CodArtxProv_DV,Unidades_DV=@Unidades_DV,PrecioUnitario_DV=@PrecioUnitario_DV
WHERE CodVenta_DV=@CodVenta_DV
GO

-------------------------------------------------------- TRIGGERS --------------------------------------------------------

---ACTULIZAR STOCK DE PRODUCTOS

CREATE TRIGGER TR_ACTUALIZARSTOCK
ON DETALLEVENTAS
FOR INSERT
AS
	BEGIN
	DECLARE @CODPROD VARCHAR(5),@CANT INT,@Stock INT
	SELECT @CODPROD=CodArtxProv_DV,@CANT=Unidades_DV FROM inserted
	SELECT @Stock=Stock_AxP FROM ARTXPROV WHERE Cod_AxP=@CODPROD
	IF(@CANT<=@Stock)
	UPDATE ARTXPROV SET Stock_AxP=Stock_AxP-@CANT
	WHERE Cod_AxP=@CODPROD
	ELSE
	ROLLBACK
	END
GO

----ELIMINADO
/*---CALUCLO TOTAL VENTA
CREATE TRIGGER TR_CALCULOTOTLAVENTA
ON DETALLEVENTAS
AFTER INSERT
AS
	BEGIN
	UPDATE VENTAS SET Total_V = Total_V + (SELECT Unidades_DV * PrecioUnitario_DV FROM inserted)
	WHERE Cod_V = (SELECT CodVenta_DV FROM inserted)
END
GO
*/


--PONER EL PRECIO AUTOMATICO 
/*CREATE TRIGGER TR_INSERTARPRECIO 
ON DETALLEVENTAS
AFTER INSERT 
AS
BEGIN 
*/
--INSERTAR PRECIO ARTICULO 
/*DECLARE @PRECIO DECIMAL (8,2), @CODARTICULO CHAR(5),@CODVENTA INT, @CANTVENTA INT
SELECT @CODARTICULO=CodArtxProv_DV,@CANTVENTA=Unidades_DV,@CODVENTA=CodVenta_DV
FROM INSERTED
SELECT @PRECIO=Precio_ART FROM ARTICULOS WHERE Cod_ART=@CODARTICULO
UPDATE DETALLEVENTAS SET PrecioUnitario_DV = @PRECIO WHERE CodVenta_DV = @CODVENTA AND 
CodArtxProv_DV = @CODARTICULO
--ACTUALIZACION TOTAL DE FACTURA 
UPDATE VENTAS SET Total_V= Total_V+(@PRECIO*@CANTVENTA)
WHERE Cod_V=@CODVENTA*/
/*UPDATE DETALLEVENTAS SET PrecioUnitario_DV = (SELECT PrecioUnitario_DV From inserted)
WHERE CodVenta_DV = (SELECT CodVenta_DV FROM inserted) AND 
CodArtxProv_DV = (SELECT CodArtxProv_DV FROM inserted)
--ACTUALIZACION TOTAL DE FACTURA 
UPDATE VENTAS SET Total_V = Total_V+(SELECT Unidades_DV * PrecioUnitario_DV FROM inserted)
WHERE Cod_V = (SELECT CodVenta_DV FROM inserted)
END 
GO*/

-------------------------------------------------------- INSERT --------------------------------------------------------

--CATEGORIAS
BEGIN
EXEC SPAGREGARCATEGORIA 'PER01','PERFORACION','UNIVERSAL',NULL
EXEC SPAGREGARCATEGORIA 'COR01','CORTE','UNIVERSAL',NULL
EXEC SPAGREGARCATEGORIA 'LIM01','LIMPIEZA','EXTERIOR E INTERIOR',NULL
EXEC SPAGREGARCATEGORIA 'JAR01','JARDIN','EXTERIORES',NULL
EXEC SPAGREGARCATEGORIA 'LDP01','LIJADO-PULIDO','UNIVERSAL',NULL
EXEC SPAGREGARCATEGORIA 'SOL01','SOLDADURA','METALES',NULL
END
GO

--PERFILES
BEGIN
EXEC SPAGREGARPERFIL 'ADM01','ADMINISTRADOR'
END
GO
INSERT INTO PERFILES(Cod_PER,Nombre_PER)
SELECT 'CLI01','CLIENTE' UNION
SELECT 'PRV01','PROVEEDOR'
GO
-- PROVINCIAS
BEGIN
EXEC SPAGREGARPROVINCIAS 'Buenos Aires'
EXEC SPAGREGARPROVINCIAS 'Capital Federal'
EXEC SPAGREGARPROVINCIAS 'Catamarca'
EXEC SPAGREGARPROVINCIAS 'Chaco'
EXEC SPAGREGARPROVINCIAS 'Chubut'
EXEC SPAGREGARPROVINCIAS 'Córdoba'
EXEC SPAGREGARPROVINCIAS 'Corrientes'
EXEC SPAGREGARPROVINCIAS 'Entre Ríos'
EXEC SPAGREGARPROVINCIAS 'Formosa'
EXEC SPAGREGARPROVINCIAS 'Jujuy'
EXEC SPAGREGARPROVINCIAS 'La Pampa'
EXEC SPAGREGARPROVINCIAS 'La Rioja'
EXEC SPAGREGARPROVINCIAS 'Mendoza'
EXEC SPAGREGARPROVINCIAS 'Misiones'
EXEC SPAGREGARPROVINCIAS 'Neuquén'
EXEC SPAGREGARPROVINCIAS 'Río Negro'
EXEC SPAGREGARPROVINCIAS 'Salta'
EXEC SPAGREGARPROVINCIAS 'San Juan'
EXEC SPAGREGARPROVINCIAS 'San Luis'
EXEC SPAGREGARPROVINCIAS 'Santa Cruz'
EXEC SPAGREGARPROVINCIAS 'Santa Fe'
EXEC SPAGREGARPROVINCIAS 'Santiago del Estero'
EXEC SPAGREGARPROVINCIAS 'Tierra del Fuego'
EXEC SPAGREGARPROVINCIAS 'Tucumán'
END
GO
--CIUDADES
BEGIN
EXEC SPAGREGARCIUDADES '1',	'Adolfo Gonzales Chaves, Buenos Aires'
EXEC SPAGREGARCIUDADES '1',	'Alejandro Korn'
EXEC SPAGREGARCIUDADES '1',	'América'
EXEC SPAGREGARCIUDADES '1',	'Arrecifes'
EXEC SPAGREGARCIUDADES '1',	'Avellaneda'
EXEC SPAGREGARCIUDADES '1',	'Azul'
EXEC SPAGREGARCIUDADES '1',	'Bahía Blanca'
EXEC SPAGREGARCIUDADES '1',	'Balcarce'
EXEC SPAGREGARCIUDADES '1',	'Banfield'
EXEC SPAGREGARCIUDADES '1',	'Béccar'
EXEC SPAGREGARCIUDADES '1',	'Benito Juárez'
EXEC SPAGREGARCIUDADES '1',	'Berazategui'
EXEC SPAGREGARCIUDADES '1',	'Berisso'
EXEC SPAGREGARCIUDADES '1',	'Bragado'
EXEC SPAGREGARCIUDADES '1',	'Buenos Aires'
EXEC SPAGREGARCIUDADES '1',	'Burzaco'
EXEC SPAGREGARCIUDADES '1',	'Campana'
EXEC SPAGREGARCIUDADES '1',	'Cariló'
EXEC SPAGREGARCIUDADES '1',	'Carmen de Areco'
EXEC SPAGREGARCIUDADES '1',	'Carmen de Patagones'
EXEC SPAGREGARCIUDADES '1',	'Chacabuco'
EXEC SPAGREGARCIUDADES '1',	'Chivilcoy'
EXEC SPAGREGARCIUDADES '1',	'Ciudadela'
EXEC SPAGREGARCIUDADES '1',	'Ciudad Jardín Lomas del Palomar'
EXEC SPAGREGARCIUDADES '1',	'Colonia Lapin'
EXEC SPAGREGARCIUDADES '1',	'Coronel Martínez de Hoz'
EXEC SPAGREGARCIUDADES '1',	'Coronel Pringles'
EXEC SPAGREGARCIUDADES '1',	'Dolores'
EXEC SPAGREGARCIUDADES '1',	'El Palomar'
EXEC SPAGREGARCIUDADES '1',	'Ensenada'
EXEC SPAGREGARCIUDADES '1',	'Ezeiza'
EXEC SPAGREGARCIUDADES '1',	'Florencio Varela'
EXEC SPAGREGARCIUDADES '1',	'Florida Este'
EXEC SPAGREGARCIUDADES '1',	'General Alvear'
EXEC SPAGREGARCIUDADES '1',	'General Las Heras'
EXEC SPAGREGARCIUDADES '1',	'General Lavalle'
EXEC SPAGREGARCIUDADES '1',	'General Rodríguez'
EXEC SPAGREGARCIUDADES '1',	'General Villegas'
EXEC SPAGREGARCIUDADES '1',	'Guaminí'
EXEC SPAGREGARCIUDADES '1',	'Hurlingham'
EXEC SPAGREGARCIUDADES '1',	'Ingeniero Maschwitz'
EXEC SPAGREGARCIUDADES '1',	'Ituzaingó'
EXEC SPAGREGARCIUDADES '1',	'José C. Paz'
EXEC SPAGREGARCIUDADES '1',	'Junín'
EXEC SPAGREGARCIUDADES '1',	'La Lucila'
EXEC SPAGREGARCIUDADES '1',	'Lanús'
EXEC SPAGREGARCIUDADES '1',	'La Plata'
EXEC SPAGREGARCIUDADES '1',	'Las Flores'
EXEC SPAGREGARCIUDADES '1',	'Leandro N. Alem'
EXEC SPAGREGARCIUDADES '1',	'Lobos'
EXEC SPAGREGARCIUDADES '1',	'Lomas de Zamora'
EXEC SPAGREGARCIUDADES '1',	'Luján'
EXEC SPAGREGARCIUDADES '1',	'Mar del Plata'
EXEC SPAGREGARCIUDADES '1',	'Martínez'
EXEC SPAGREGARCIUDADES '1',	'Merlo'
EXEC SPAGREGARCIUDADES '1',	'Miramar'
EXEC SPAGREGARCIUDADES '1',	'Monte Grande'
EXEC SPAGREGARCIUDADES '1',	'Morón'
EXEC SPAGREGARCIUDADES '1',	'Munro'
EXEC SPAGREGARCIUDADES '1',	'Necochea'
EXEC SPAGREGARCIUDADES '1',	'Nueve de Julio'
EXEC SPAGREGARCIUDADES '1',	'Olavarría'
EXEC SPAGREGARCIUDADES '1',	'Olivos'
EXEC SPAGREGARCIUDADES '1',	'Parque San Martín'
EXEC SPAGREGARCIUDADES '1',	'Pehuajó'
EXEC SPAGREGARCIUDADES '1',	'Pergamino'
EXEC SPAGREGARCIUDADES '1',	'Pigüé'
EXEC SPAGREGARCIUDADES '1',	'Pilar'
EXEC SPAGREGARCIUDADES '1',	'Pinamar'
EXEC SPAGREGARCIUDADES '1',	'Rafael Calzada'
EXEC SPAGREGARCIUDADES '1',	'Quilmes'
EXEC SPAGREGARCIUDADES '1',	'San Antonio de Padua'
EXEC SPAGREGARCIUDADES '1',	'San Fernando'
EXEC SPAGREGARCIUDADES '1',	'San Isidro'
EXEC SPAGREGARCIUDADES '1',	'San Justo'
EXEC SPAGREGARCIUDADES '1',	'San Miguel del Monte'
EXEC SPAGREGARCIUDADES '1',	'San Nicolás de los Arroyos'
EXEC SPAGREGARCIUDADES '1',	'Santos Lugares'
EXEC SPAGREGARCIUDADES '1',	'Sarandí'
EXEC SPAGREGARCIUDADES '1',	'Tandil'
EXEC SPAGREGARCIUDADES '1',	'Tigre'
EXEC SPAGREGARCIUDADES '1',	'Trenque Lauquen'
EXEC SPAGREGARCIUDADES '1',	'Tres Arroyos'
EXEC SPAGREGARCIUDADES '1',	'Tres de Febrero'
EXEC SPAGREGARCIUDADES '1',	'Valentín Alsina'
EXEC SPAGREGARCIUDADES '1',	'Villa Gesell'
EXEC SPAGREGARCIUDADES '1',	'Villa Fiorito'
EXEC SPAGREGARCIUDADES '1',	'Villa Martelli'
EXEC SPAGREGARCIUDADES '1',	'Villa Mercedes'
EXEC SPAGREGARCIUDADES '1',	'Zárate'

EXEC SPAGREGARCIUDADES '2',	'Agronomía'
EXEC SPAGREGARCIUDADES '2',	'Almagro'
EXEC SPAGREGARCIUDADES '2',	'Balvanera'
EXEC SPAGREGARCIUDADES '2',	'Barracas'
EXEC SPAGREGARCIUDADES '2',	'Belgrano'
EXEC SPAGREGARCIUDADES '2',	'Boedo'
EXEC SPAGREGARCIUDADES '2',	'Caballito'
EXEC SPAGREGARCIUDADES '2',	'Chacarita'
EXEC SPAGREGARCIUDADES '2',	'Coghlan'
EXEC SPAGREGARCIUDADES '2',	'Colegiales'
EXEC SPAGREGARCIUDADES '2',	'Constitución'
EXEC SPAGREGARCIUDADES '2',	'Flores'
EXEC SPAGREGARCIUDADES '2',	'Floresta'
EXEC SPAGREGARCIUDADES '2',	'La Boca'
EXEC SPAGREGARCIUDADES '2',	'La Paternal'
EXEC SPAGREGARCIUDADES '2',	'Liniers'
EXEC SPAGREGARCIUDADES '2',	'Mataderos'
EXEC SPAGREGARCIUDADES '2',	'Monte Castro'
EXEC SPAGREGARCIUDADES '2',	'Montserrat'
EXEC SPAGREGARCIUDADES '2',	'Nueva Pompeya'
EXEC SPAGREGARCIUDADES '2',	'Nuñez'
EXEC SPAGREGARCIUDADES '2',	'Palermo'
EXEC SPAGREGARCIUDADES '2',	'Parque Avellaneda'
EXEC SPAGREGARCIUDADES '2',	'Parque Chacabuco'
EXEC SPAGREGARCIUDADES '2',	'Parque Chas'
EXEC SPAGREGARCIUDADES '2',	'Parque Patricios'
EXEC SPAGREGARCIUDADES '2',	'Puerto Madero'
EXEC SPAGREGARCIUDADES '2',	'Recoleta'
EXEC SPAGREGARCIUDADES '2',	'Retiro'
EXEC SPAGREGARCIUDADES '2',	'Saavedra'
EXEC SPAGREGARCIUDADES '2',	'San Cristóbal'
EXEC SPAGREGARCIUDADES '2',	'San Nicolás'
EXEC SPAGREGARCIUDADES '2',	'San Telmo'
EXEC SPAGREGARCIUDADES '2',	'Versalles'
EXEC SPAGREGARCIUDADES '2',	'Villa Crespo'
EXEC SPAGREGARCIUDADES '2',	'Villa Devoto'
EXEC SPAGREGARCIUDADES '2',	'Villa General Mitre'
EXEC SPAGREGARCIUDADES '2',	'Villa Lugano'
EXEC SPAGREGARCIUDADES '2',	'Villa Luro'
EXEC SPAGREGARCIUDADES '2',	'Villa Ortúzar'
EXEC SPAGREGARCIUDADES '2',	'Villa Pueyrredón'
EXEC SPAGREGARCIUDADES '2',	'Villa Real'
EXEC SPAGREGARCIUDADES '2',	'Villa Riachuelo'
EXEC SPAGREGARCIUDADES '2',	'Villa Santa Rita'
EXEC SPAGREGARCIUDADES '2',	'Villa Soldati'
EXEC SPAGREGARCIUDADES '2',	'Villa Urquiza'
EXEC SPAGREGARCIUDADES '2',	'Villa del Parque'
EXEC SPAGREGARCIUDADES '2',	'Vélez Sarsfield'
	
EXEC SPAGREGARCIUDADES '3',	'San Fernando del Valle de Catamarca'
EXEC SPAGREGARCIUDADES '3',	'Andalgalá'
EXEC SPAGREGARCIUDADES '3',	'Belén'
EXEC SPAGREGARCIUDADES '3',	'San Isidro'
EXEC SPAGREGARCIUDADES '3',	'Santa María'
EXEC SPAGREGARCIUDADES '3',	'Saujil'
EXEC SPAGREGARCIUDADES '3',	'Tinogasta'
	
EXEC SPAGREGARCIUDADES '4',	'Resistencia'
EXEC SPAGREGARCIUDADES '4',	'Barranqueras'
EXEC SPAGREGARCIUDADES '4',	'Castelli'
EXEC SPAGREGARCIUDADES '4',	'Charata'
EXEC SPAGREGARCIUDADES '4',	'General José de San Martín'
EXEC SPAGREGARCIUDADES '4',	'General Pinedo'
EXEC SPAGREGARCIUDADES '4',	'Presidencia Roque Sáenz Peña'
EXEC SPAGREGARCIUDADES '4',	'Villa Ángela'
	
EXEC SPAGREGARCIUDADES '5',	'Rawson'
EXEC SPAGREGARCIUDADES '5',	'Comodoro Rivadavia'
EXEC SPAGREGARCIUDADES '5',	'Dolavon'
EXEC SPAGREGARCIUDADES '5',	'Esquel'
EXEC SPAGREGARCIUDADES '5',	'Gaiman'
EXEC SPAGREGARCIUDADES '5',	'Puerto Madryn'
EXEC SPAGREGARCIUDADES '5',	'Puerto Pirámides'
EXEC SPAGREGARCIUDADES '5',	'Rada Tilly'
EXEC SPAGREGARCIUDADES '5',	'Sarmiento'
EXEC SPAGREGARCIUDADES '5',	'Trelew'
EXEC SPAGREGARCIUDADES '5',	'Trevelin'
	
EXEC SPAGREGARCIUDADES '6',	'Córdoba'
EXEC SPAGREGARCIUDADES '6',	'Alta Gracia'
EXEC SPAGREGARCIUDADES '6',	'Arias'
EXEC SPAGREGARCIUDADES '6',	'Arroyito'
EXEC SPAGREGARCIUDADES '6',	'Bell Ville'
EXEC SPAGREGARCIUDADES '6',	'Canals'
EXEC SPAGREGARCIUDADES '6',	'Capilla del Monte'
EXEC SPAGREGARCIUDADES '6',	'Colonia Caroya'
EXEC SPAGREGARCIUDADES '6',	'Cosquín'
EXEC SPAGREGARCIUDADES '6',	'Cruz del Eje'
EXEC SPAGREGARCIUDADES '6',	'Ischilín'
EXEC SPAGREGARCIUDADES '6',	'James Craik'
EXEC SPAGREGARCIUDADES '6',	'Jesús María'
EXEC SPAGREGARCIUDADES '6',	'La Carlota'
EXEC SPAGREGARCIUDADES '6',	'La Cumbre'
EXEC SPAGREGARCIUDADES '6',	'La Cumbrecita'
EXEC SPAGREGARCIUDADES '6',	'La Falda'
EXEC SPAGREGARCIUDADES '6',	'Laboulaye'
EXEC SPAGREGARCIUDADES '6',	'Laguna Larga'
EXEC SPAGREGARCIUDADES '6',	'Las Varillas'
EXEC SPAGREGARCIUDADES '6',	'Leones'
EXEC SPAGREGARCIUDADES '6',	'Levalle'
EXEC SPAGREGARCIUDADES '6',	'Mina Clavero'
EXEC SPAGREGARCIUDADES '6',	'Miramar'
EXEC SPAGREGARCIUDADES '6',	'Morteros'
EXEC SPAGREGARCIUDADES '6',	'Oncativo'
EXEC SPAGREGARCIUDADES '6',	'Quilino'
EXEC SPAGREGARCIUDADES '6',	'Río Cuarto'
EXEC SPAGREGARCIUDADES '6',	'Río Segundo'
EXEC SPAGREGARCIUDADES '6',	'Río Tercero'
EXEC SPAGREGARCIUDADES '6',	'San Francisco del Chañar'
EXEC SPAGREGARCIUDADES '6',	'San Francisco'
EXEC SPAGREGARCIUDADES '6',	'Santa Rosa de Calamuchita'
EXEC SPAGREGARCIUDADES '6',	'Tanti'
EXEC SPAGREGARCIUDADES '6',	'Unquillo'
EXEC SPAGREGARCIUDADES '6',	'Valle Hermoso'
EXEC SPAGREGARCIUDADES '6',	'Vicuña Mackenna'
EXEC SPAGREGARCIUDADES '6',	'Villa Carlos Paz'
EXEC SPAGREGARCIUDADES '6',	'Villa Cura Brochero'
EXEC SPAGREGARCIUDADES '6',	'Villa del Totoral'
EXEC SPAGREGARCIUDADES '6',	'Villa General Belgrano'
EXEC SPAGREGARCIUDADES '6',	'Villa María'
	
EXEC SPAGREGARCIUDADES '7',	'Corrientes'
EXEC SPAGREGARCIUDADES '7',	'Alvear'
EXEC SPAGREGARCIUDADES '7',	'Bella Vista'
EXEC SPAGREGARCIUDADES '7',	'Curuzú Cuatiá'
EXEC SPAGREGARCIUDADES '7',	'Empedrado'
EXEC SPAGREGARCIUDADES '7',	'Esquina'
EXEC SPAGREGARCIUDADES '7',	'Gobernador Virasoro'
EXEC SPAGREGARCIUDADES '7',	'Goya'
EXEC SPAGREGARCIUDADES '7',	'Itatí'
EXEC SPAGREGARCIUDADES '7',	'Ituzaingó'
EXEC SPAGREGARCIUDADES '7',	'Paso de los Libres'
EXEC SPAGREGARCIUDADES '7',	'Santo Tomé'
EXEC SPAGREGARCIUDADES '7',	'Saladas'
EXEC SPAGREGARCIUDADES '7',	'Santa Lucía'
EXEC SPAGREGARCIUDADES '7',	'Sauce'
	
EXEC SPAGREGARCIUDADES '8',	'Paraná'
EXEC SPAGREGARCIUDADES '8',	'Basavilbaso'
EXEC SPAGREGARCIUDADES '8',	'Chajarí'
EXEC SPAGREGARCIUDADES '8',	'Colón'
EXEC SPAGREGARCIUDADES '8',	'Concepción del Uruguay'
EXEC SPAGREGARCIUDADES '8',	'Concordia'
EXEC SPAGREGARCIUDADES '8',	'Crespo'
EXEC SPAGREGARCIUDADES '8',	'Diamante'
EXEC SPAGREGARCIUDADES '8',	'Federación'
EXEC SPAGREGARCIUDADES '8',	'Gualeguay'
EXEC SPAGREGARCIUDADES '8',	'Gualeguaychú'
EXEC SPAGREGARCIUDADES '8',	'La Paz'
EXEC SPAGREGARCIUDADES '8',	'Larroque'
EXEC SPAGREGARCIUDADES '8',	'Libertador San Martín'
EXEC SPAGREGARCIUDADES '8',	'Puiggari'
EXEC SPAGREGARCIUDADES '8',	'San José'
EXEC SPAGREGARCIUDADES '8',	'Urdinarrain'
EXEC SPAGREGARCIUDADES '8',	'Victoria'
EXEC SPAGREGARCIUDADES '8',	'Villa Elisa'
EXEC SPAGREGARCIUDADES '8',	'Villa Paranacito'
EXEC SPAGREGARCIUDADES '8',	'Villaguay'
	
EXEC SPAGREGARCIUDADES '9',	'Formosa'
EXEC SPAGREGARCIUDADES '9',	'Clorinda'
EXEC SPAGREGARCIUDADES '9',	'Ibarreta'
EXEC SPAGREGARCIUDADES '9',	'Las Lomitas'
EXEC SPAGREGARCIUDADES '9',	'Puerto Pilcomayo'
	
EXEC SPAGREGARCIUDADES '10',	'San Salvador de Jujuy'
EXEC SPAGREGARCIUDADES '10',	'General San Martín'
EXEC SPAGREGARCIUDADES '10',	'Humahuaca'
EXEC SPAGREGARCIUDADES '10',	'León'
EXEC SPAGREGARCIUDADES '10',	'La Quiaca'
EXEC SPAGREGARCIUDADES '10',	'San Pedro'
EXEC SPAGREGARCIUDADES '10',	'Tilcara'
	
EXEC SPAGREGARCIUDADES '11',	'Santa Rosa'
EXEC SPAGREGARCIUDADES '11',	'Eduardo Castex'
EXEC SPAGREGARCIUDADES '11',	'General Pico'
EXEC SPAGREGARCIUDADES '11',	'Guatraché'
EXEC SPAGREGARCIUDADES '11',	'Macachín'
EXEC SPAGREGARCIUDADES '11',	'Realicó'
EXEC SPAGREGARCIUDADES '11',	'Santa Isabel'
	
EXEC SPAGREGARCIUDADES '12',	'La Rioja'
EXEC SPAGREGARCIUDADES '12',	'Aimogasta'
EXEC SPAGREGARCIUDADES '12',	'Anillaco'
EXEC SPAGREGARCIUDADES '12',	'Chepes'
EXEC SPAGREGARCIUDADES '12',	'Chilecito'
EXEC SPAGREGARCIUDADES '12',	'El Chamical'
EXEC SPAGREGARCIUDADES '12',	'Famatina'
EXEC SPAGREGARCIUDADES '12',	'Patquía'
EXEC SPAGREGARCIUDADES '12',	'Villa Unión'
	
EXEC SPAGREGARCIUDADES '13',	'Mendoza'
EXEC SPAGREGARCIUDADES '13',	'General Alvear'
EXEC SPAGREGARCIUDADES '13',	'Godoy Cruz'
EXEC SPAGREGARCIUDADES '13',	'La Paz'
EXEC SPAGREGARCIUDADES '13',	'Luján de Cuyo'
EXEC SPAGREGARCIUDADES '13',	'Malargüe'
EXEC SPAGREGARCIUDADES '13',	'Palmira'
EXEC SPAGREGARCIUDADES '13',	'Puente del Inca'
EXEC SPAGREGARCIUDADES '13',	'Punta de Vacas'
EXEC SPAGREGARCIUDADES '13',	'Rivadavia'
EXEC SPAGREGARCIUDADES '13',	'San Martín'
EXEC SPAGREGARCIUDADES '13',	'San Rafael'
EXEC SPAGREGARCIUDADES '13',	'Tunuyán'
EXEC SPAGREGARCIUDADES '13',	'Tupungato'
EXEC SPAGREGARCIUDADES '13',	'Uspallata'
	
EXEC SPAGREGARCIUDADES '14',	'Posadas'
EXEC SPAGREGARCIUDADES '14',	'Andresito'
EXEC SPAGREGARCIUDADES '14',	'Apóstoles'
EXEC SPAGREGARCIUDADES '14',	'Bernardo de Irigoyen'
EXEC SPAGREGARCIUDADES '14',	'Candelaria'
EXEC SPAGREGARCIUDADES '14',	'Eldorado'
EXEC SPAGREGARCIUDADES '14',	'Montecarlo'
EXEC SPAGREGARCIUDADES '14',	'Oberá'
EXEC SPAGREGARCIUDADES '14',	'Puerto Iguazú'
	
EXEC SPAGREGARCIUDADES '15',	'Neuquén'
EXEC SPAGREGARCIUDADES '15',	'Aluminé'
EXEC SPAGREGARCIUDADES '15',	'Centenario'
EXEC SPAGREGARCIUDADES '15',	'Chos Malal'
EXEC SPAGREGARCIUDADES '15',	'Cutral Có'
EXEC SPAGREGARCIUDADES '15',	'Junín de los Andes'
EXEC SPAGREGARCIUDADES '15',	'Loncopué'
EXEC SPAGREGARCIUDADES '15',	'Piedra del Águila'
EXEC SPAGREGARCIUDADES '15',	'Plottier'
EXEC SPAGREGARCIUDADES '15',	'San Martín de los Andes'
EXEC SPAGREGARCIUDADES '15',	'Villa La Angostura'
EXEC SPAGREGARCIUDADES '15',	'Zapala'
	
EXEC SPAGREGARCIUDADES '16',	'Viedma'
EXEC SPAGREGARCIUDADES '16',	'Choele Choel'
EXEC SPAGREGARCIUDADES '16',	'Cipolletti'
EXEC SPAGREGARCIUDADES '16',	'El Bolsón'
EXEC SPAGREGARCIUDADES '16',	'General Roca'
EXEC SPAGREGARCIUDADES '16',	'Ingeniero Jacobacci'
EXEC SPAGREGARCIUDADES '16',	'San Antonio Oeste'
EXEC SPAGREGARCIUDADES '16',	'San Carlos de Bariloche'
EXEC SPAGREGARCIUDADES '16',	'Sierra Grande'
EXEC SPAGREGARCIUDADES '16',	'Villa Regina'
	
EXEC SPAGREGARCIUDADES '17',	'Salta'
EXEC SPAGREGARCIUDADES '17',	'Cachi'
EXEC SPAGREGARCIUDADES '17',	'Cafayate'
EXEC SPAGREGARCIUDADES '17',	'General Güemes'
EXEC SPAGREGARCIUDADES '17',	'Salvador Mazza'
EXEC SPAGREGARCIUDADES '17',	'San Antonio de los Cobres'
EXEC SPAGREGARCIUDADES '17',	'San Ramón de la Nueva Orán'
EXEC SPAGREGARCIUDADES '17',	'Tartagal'
	
EXEC SPAGREGARCIUDADES '18',	'San Juan'
EXEC SPAGREGARCIUDADES '18',	'Calingasta'
EXEC SPAGREGARCIUDADES '18',	'Caucete'
EXEC SPAGREGARCIUDADES '18',	'San José de Jáchal'
EXEC SPAGREGARCIUDADES '18',	'Villa Media Agua'
EXEC SPAGREGARCIUDADES '18',	'Zonda'
EXEC SPAGREGARCIUDADES '18',	'Albardón'
EXEC SPAGREGARCIUDADES '18',	'9 de Julio'
EXEC SPAGREGARCIUDADES '18',	'Villa Krause'
EXEC SPAGREGARCIUDADES '18',	'Villa Paula Albarracín de Sarmiento'
EXEC SPAGREGARCIUDADES '18',	'Aberastain'
	
EXEC SPAGREGARCIUDADES '19',	'San Luis'
EXEC SPAGREGARCIUDADES '19',	'Merlo'
EXEC SPAGREGARCIUDADES '19',	'La Punta'
EXEC SPAGREGARCIUDADES '19',	'San Francisco del Monte de Oro'
EXEC SPAGREGARCIUDADES '19',	'El Trapiche'
EXEC SPAGREGARCIUDADES '19',	'Villa Mercedes'
	
EXEC SPAGREGARCIUDADES '20',	'Comandante Luis Piedrabuena'
EXEC SPAGREGARCIUDADES '20',	'Puerto Santa Cruz'
EXEC SPAGREGARCIUDADES '20',	'Caleta Olivia'
EXEC SPAGREGARCIUDADES '20',	'El Calafate'
EXEC SPAGREGARCIUDADES '20',	'El Chaltén'
EXEC SPAGREGARCIUDADES '20',	'Gobernador Gregores'
EXEC SPAGREGARCIUDADES '20',	'Los Antiguos'
EXEC SPAGREGARCIUDADES '20',	'Pico Truncado'
EXEC SPAGREGARCIUDADES '20',	'Puerto Deseado'
EXEC SPAGREGARCIUDADES '20',	'Puerto San Julián'
EXEC SPAGREGARCIUDADES '20',	'Río Gallegos'
EXEC SPAGREGARCIUDADES '20',	'Río Turbio'
	
EXEC SPAGREGARCIUDADES '21',	'Santa Fe'
EXEC SPAGREGARCIUDADES '21',	'Cañada de Gómez'
EXEC SPAGREGARCIUDADES '21',	'Carlos Pellegrini'
EXEC SPAGREGARCIUDADES '21',	'Coronda'
EXEC SPAGREGARCIUDADES '21',	'Esperanza'
EXEC SPAGREGARCIUDADES '21',	'Funes'
EXEC SPAGREGARCIUDADES '21',	'Frontera'
EXEC SPAGREGARCIUDADES '21',	'Rafaela'
EXEC SPAGREGARCIUDADES '21',	'Reconquista'
EXEC SPAGREGARCIUDADES '21',	'Rosario'
EXEC SPAGREGARCIUDADES '21',	'Rufino'
EXEC SPAGREGARCIUDADES '21',	'San Carlos Centro'
EXEC SPAGREGARCIUDADES '21',	'San Lorenzo'
EXEC SPAGREGARCIUDADES '21',	'Santo Tomé'
EXEC SPAGREGARCIUDADES '21',	'Sauce Viejo'
EXEC SPAGREGARCIUDADES '21',	'Sunchales'
EXEC SPAGREGARCIUDADES '21',	'Venado Tuerto'
EXEC SPAGREGARCIUDADES '21',	'Villa Cañás'
EXEC SPAGREGARCIUDADES '21',	'Villa Constitución'
	
EXEC SPAGREGARCIUDADES '22',	'Santiago del Estero'
EXEC SPAGREGARCIUDADES '22',	'Añatuya'
EXEC SPAGREGARCIUDADES '22',	'Frías'
EXEC SPAGREGARCIUDADES '22',	'Isca Yacu'
EXEC SPAGREGARCIUDADES '22',	'La Banda'
EXEC SPAGREGARCIUDADES '22',	'Loreto'
EXEC SPAGREGARCIUDADES '22',	'Río Hondo'
	
EXEC SPAGREGARCIUDADES '23',	'Ushuaia'
EXEC SPAGREGARCIUDADES '23',	'Río Grande'
EXEC SPAGREGARCIUDADES '23',	'Tolhuin'
	
EXEC SPAGREGARCIUDADES '24',	'San Miguel de Tucumán'
EXEC SPAGREGARCIUDADES '24',	'Aguilares'
EXEC SPAGREGARCIUDADES '24',	'Banda del Río Salí'
EXEC SPAGREGARCIUDADES '24',	'Concepción'
EXEC SPAGREGARCIUDADES '24',	'Famaillá'
EXEC SPAGREGARCIUDADES '24',	'Lules'
EXEC SPAGREGARCIUDADES '24',	'Monteros'
EXEC SPAGREGARCIUDADES '24',	'Simoca'
EXEC SPAGREGARCIUDADES '24',	'Tafí del Valle'
EXEC SPAGREGARCIUDADES '24',	'Tafí Viejo'
EXEC SPAGREGARCIUDADES '24',	'Yerba Buena'

END 
GO
--MARCAS
BEGIN
EXEC SPAGREGARMARCA 'BAD01','BLACK AND DECKER','BLACK AND DECKER SRL',NULL
EXEC SPAGREGARMARCA 'HAM02','HAMILTON','HAMILTON S.A',NULL
EXEC SPAGREGARMARCA 'STA03','STANLEY','STANLEY S.A',NULL
EXEC SPAGREGARMARCA 'BOS04','BOSCH','BOSCH SRL',NULL
EXEC SPAGREGARMARCA 'LUS05','LUSQTOFF','LUSQTOFF MFS',NULL
EXEC SPAGREGARMARCA 'PHI06','PHILCO','PHILCO SDA',NULL
END
INSERT INTO MARCAS(Cod_MA,Nombre_MA,Descripcion_MA)
SELECT  'VAL07','VALUE','VALUE S.A' UNION
SELECT  'COL08','COOLTECH', 'COOLTECH S.A'
GO
--MEDIOPAGO
BEGIN 
EXEC SPAGREGARMEDIOPAGOS '1','Efectivo','Método de pago en efectivo'
EXEC SPAGREGARMEDIOPAGOS '2', 'Débito','Método de pago a través de tarjeta de débito'
EXEC SPAGREGARMEDIOPAGOS '3','Crédito','Método de pago a través de tarjeta de crédito'
END
GO

--USUARIOS
BEGIN 
EXEC SPAGREGARUSUARIO '34484730069','PRV01',NULL,NULL,'01129085617','provCarlos@gmail.com','Pass123',1,4,NULL,'Herramientas Carlos'
EXEC SPAGREGARUSUARIO '24760315490','PRV01',NULL,NULL,'01147264400','provHerr@gmail.com','Pass123',2,98,NULL,'HerrMan'
EXEC SPAGREGARUSUARIO '24624687430','PRV01',NULL,NULL,'01143487724','provMonte@gmail.com','Pass123',3,140,NULL,'MonteHerramientas'
EXEC SPAGREGARUSUARIO '30903978283','PRV01',NULL,NULL,'01145541122','provConst@gmail.com','Pass123',4,147,NULL,'Constructores'
EXEC SPAGREGARUSUARIO '34125474677','PRV01',NULL,NULL,'29085617','provTodo@gmail.com','Pass123',5,160,NULL,'TodoManualHerr'
EXEC SPAGREGARUSUARIO '20325855655','ADM01','Jorge','Bossio','0112565856','jorge@gmail.com','Pass123',3,141,NULL,NULL
END
GO

BEGIN
INSERT INTO USUARIOS(Cuit_USU,PerfilCod_USU,Nombre_USU,Apellido_USU,Telefono_USU,Email_USU,Password_USU,CodProvincia_USU,CodCiudad_USU,Imagen_USU,RazonSocial_USU)
SELECT  '20286558986','CLI01','Osvaldo','Alvarez','01126589242','osvaldo@gmail.com','Pass123',1,25,NULL,NULL UNION
SELECT  '27315547332','CLI01','Maria','Carrizo','0113659542','maria@gmail.com','Pass123',6,166,NULL,NULL
END
GO
--PROVEEDORES
BEGIN
EXEC SPAGREGARPROVEEDORES '34484730069', '1', 'Herramientas Carlos', '01129085617'
EXEC SPAGREGARPROVEEDORES '24760315490', '2', 'HerrMan', '01147264400'
EXEC SPAGREGARPROVEEDORES '24624687430', '3', 'MonteHerramientas', '01143487724'
EXEC SPAGREGARPROVEEDORES '30903978283', '4', 'Constructores', '01145541122'
EXEC SPAGREGARPROVEEDORES '34125474677', '5', 'TodoManualHerr', '29085617'
END
--ARTICULOS
BEGIN
EXEC SPAGREGARARTICULO '1','HAM02','PER01','Rotomartillo','Taladrar SIN percusión, Taladrar con percusión, Cincelar','42104.00','~/Imagenes/1.jpg',1
EXEC SPAGREGARARTICULO '2','HAM02','PER01','Taladro','1650 rpm','50585.00','~/Imagenes/2.jpg',1
EXEC SPAGREGARARTICULO '3','BAD01','COR01','Amoladora','11000 rpm','11100.00','~/Imagenes/3.jpg',1
EXEC SPAGREGARARTICULO '4','BAD01','LIM01','Hidrolavadora','1450psi de presión','24517.00','~/Imagenes/4.jpg',1
EXEC SPAGREGARARTICULO '5','STA03','JAR01','Sopladora','Eléctrica 600W','24898.00','~/Imagenes/5.jpg',1
EXEC SPAGREGARARTICULO '6','STA03','LDP01','Lijadora','Sistema velcro','17460.00','~/Imagenes/6.jpg',1
EXEC SPAGREGARARTICULO '7','BOS04','PER01','Taladro','Taladrar CON percusión, Cincelar','15723.00','~/Imagenes/7.jpg',1
EXEC SPAGREGARARTICULO '8','BOS04','COR01','Sierra circular','Madera, 6000 rpm','21899.00','~/Imagenes/8.jpg',1
EXEC SPAGREGARARTICULO '9','LUS05','SOL01','Soldadora','Inverter Flux','47855.00','~/Imagenes/9.jpg',1
EXEC SPAGREGARARTICULO '10','LUS05','COR01','Motosierra','11000 rpm','22562.00','~/Imagenes/10.jpg',1
END

INSERT INTO ARTICULOS(Cod_ART,MarcaCod_ART,CatCod_ART,Nombre_ART,Descripcion_ART,Precio_ART,Imagen_ART,Estado_ART)
SELECT '11','PHI06','JAR01','Sopladora','Eléctrica 2600W ','13523.00','~/Imagenes/11.jpg',1 UNION
SELECT '12','PHI06','COR01','Cortadora De Pasto','Bolsa recolectora de 1300W','29865.00','~/Imagenes/12.jpg',1
GO

--ARTXPROV
BEGIN
EXEC SPAGREGARARTXPROV 'ROT01','34484730069','1','18000','20'
EXEC SPAGREGARARTXPROV 'TAL01','34484730069','2','20000','20'
EXEC SPAGREGARARTXPROV 'AMO01','34484730069','3','30000','20'
EXEC SPAGREGARARTXPROV 'HIDR1','34484730069','4','24898','20'
EXEC SPAGREGARARTXPROV 'SOP01','34484730069','5','11325','20'
EXEC SPAGREGARARTXPROV 'LIJ01','34484730069','6','8950','20'
EXEC SPAGREGARARTXPROV 'TAL02','34484730069','7','8500','20'
EXEC SPAGREGARARTXPROV 'SIE01','34484730069','8','16850','20'
EXEC SPAGREGARARTXPROV 'SOL01','34484730069','9','13584','20'
EXEC SPAGREGARARTXPROV 'MOT01','34484730069','10','27000','20'
EXEC SPAGREGARARTXPROV 'SOP02','34484730069','11','10358','20'
EXEC SPAGREGARARTXPROV 'COR01','34484730069','12','29865','20'
END
GO

--VENTAS
BEGIN
EXEC SPAGREGARVENTAS '27315547332',1,'10.10.2020','61121'
EXEC SPAGREGARVENTAS '20286558986',1,'12.10.2020','16850'
EXEC SPAGREGARVENTAS '27315547332',1,'05.06.2021','146230'
EXEC SPAGREGARVENTAS '20286558986',1,'05.09.2021','146230'
END
GO

--DETALLEVENTAS
BEGIN
EXEC SPDETALLEVENTAS '1','HIDR1',2,'24898'
EXEC SPDETALLEVENTAS '1','SOP01',1,'11325'
EXEC SPDETALLEVENTAS '2','SIE01',1,'16850'
EXEC SPDETALLEVENTAS '3','AMO01',2,'30000'
EXEC SPDETALLEVENTAS '3','TAL02',1,'8500'
EXEC SPDETALLEVENTAS '3','COR01',2,'29865'
EXEC SPDETALLEVENTAS '3','ROT01',1,'18000'
EXEC SPDETALLEVENTAS '4','ROT01',1,'18000'
END
GO

--- ----------------------------------------CONSULTAS--------------------------------------------------------------------------------------
--CANTIDAD DE VENTAS MOSTRANDO CODIG0 DE VENTA, CANTIDAD DE ARTICULOS COMPRADOS Y MONTO
SELECT CodVenta_DV AS [CODIGO VENTA] , COUNT(*) AS [CANTIDAD DE VENTAS],SUM(Unidades_DV) AS [TOTAL DE UNIDADES],SUM(PrecioUnitario_DV*Unidades_DV) AS [MONTO] FROM DETALLEVENTAS GROUP BY CodVenta_DV
GO
--MOSTRAR DATOS DE CLIENTES DATOS DE CLIENTES
SELECT Nombre_USU AS [NOMBRE], Apellido_USU AS [APELLIDO], Email_USU AS [EMAIL]
FROM USUARIOS WHERE PerfilCod_USU=(SELECT Cod_PER FROM PERFILES WHERE Cod_PER='CLI1')
GO
--MOSTRAR ARTICULOS DADOS DE BAJA 
SELECT Nombre_ART AS [NOMBRE], Descripcion_ART AS [DESCRIPCION ]
FROM ARTICULOS WHERE Estado_ART=1
GO
--ARTICULOS MAYORES DE UNA DETERMINADA CANTIDAD DE STOCK 
SELECT Nombre_ART AS [NOMBRE], Stock_AxP AS [STOCK]
FROM ARTXPROV INNER JOIN ARTICULOS ON ARTICULOS.Cod_ART=ARTXPROV.CodArt_AxP 
WHERE Stock_AxP>10
ORDER BY Nombre_ART
GO

SELECT * FROM DETALLEVENTAS  WHERE CodVenta_DV = 1
USE DBFERRETERIA
GO
SELECT MAX( Cod_V)
FROM VENTAS where CuitCli_V='20325855655         '
GO